// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"database/sql"
	"time"
)

type Product struct {
	ID          int32     `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Price       string    `json:"price"`
	Quantity    int32     `json:"quantity"`
	StoreID     int32     `json:"storeID"`
	CreatedAt   time.Time `json:"createdAt"`
}

type Sale struct {
	ID           int32     `json:"id"`
	ProductID    int32     `json:"productID"`
	SaleDate     time.Time `json:"saleDate"`
	QuantitySold int32     `json:"quantitySold"`
	CreatedAt    time.Time `json:"createdAt"`
}

type StockAlert struct {
	ID            int32         `json:"id"`
	ProductID     sql.NullInt32 `json:"productID"`
	SupplierID    sql.NullInt32 `json:"supplierID"`
	AlertQuantity int32         `json:"alertQuantity"`
	CreatedAt     time.Time     `json:"createdAt"`
}

type Store struct {
	ID             int32     `json:"id"`
	Name           string    `json:"name"`
	Address        string    `json:"address"`
	ContactEmail   string    `json:"contactEmail"`
	ContactPhone   string    `json:"contactPhone"`
	HashedPassword string    `json:"hashedPassword"`
	CreatedAt      time.Time `json:"createdAt"`
}

type Supplier struct {
	ID           int32     `json:"id"`
	Name         string    `json:"name"`
	Address      string    `json:"address"`
	Email        string    `json:"email"`
	ContactPhone string    `json:"contactPhone"`
	CreatedAt    time.Time `json:"createdAt"`
}
