// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: product.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
  name, 
  description, 
  price, 
  store_id,
  quantity
) values  (
  $1, $2, $3, $4, $5)
RETURNING id, name, description, price, quantity, store_id, created_at
`

type CreateProductParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       string `json:"price"`
	StoreID     int64  `json:"storeID"`
	Quantity    int32  `json:"quantity"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.StoreID,
		arg.Quantity,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Quantity,
		&i.StoreID,
		&i.CreatedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, description, price, quantity, store_id, created_at FROM products WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Quantity,
		&i.StoreID,
		&i.CreatedAt,
	)
	return i, err
}

const getProductForUpdate = `-- name: GetProductForUpdate :one
SELECT id, name, description, price, quantity, store_id, created_at FROM products WHERE id = $1 LIMIT 1 FOR UPDATE FOR NO KEY UPDATE
`

func (q *Queries) GetProductForUpdate(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductForUpdate, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Quantity,
		&i.StoreID,
		&i.CreatedAt,
	)
	return i, err
}

const getProductsWithJoinWithStore = `-- name: GetProductsWithJoinWithStore :many
  SELECT products.id, products.name, products.description, products.price, products.quantity, products.store_id, products.created_at, stores.id, stores.name, stores.address, stores.contact_email, stores.contact_phone, stores.hashed_password, stores.created_at FROM products INNER JOIN stores ON products.store_id = stores.id 
  ORDER BY products.id
  LIMIT $1
  OFFSET $2
`

type GetProductsWithJoinWithStoreParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetProductsWithJoinWithStoreRow struct {
	ID             int64     `json:"id"`
	Name           string    `json:"name"`
	Description    string    `json:"description"`
	Price          string    `json:"price"`
	Quantity       int32     `json:"quantity"`
	StoreID        int64     `json:"storeID"`
	CreatedAt      time.Time `json:"createdAt"`
	ID_2           int64     `json:"id2"`
	Name_2         string    `json:"name2"`
	Address        string    `json:"address"`
	ContactEmail   string    `json:"contactEmail"`
	ContactPhone   string    `json:"contactPhone"`
	HashedPassword string    `json:"hashedPassword"`
	CreatedAt_2    time.Time `json:"createdAt2"`
}

func (q *Queries) GetProductsWithJoinWithStore(ctx context.Context, arg GetProductsWithJoinWithStoreParams) ([]GetProductsWithJoinWithStoreRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductsWithJoinWithStore, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProductsWithJoinWithStoreRow{}
	for rows.Next() {
		var i GetProductsWithJoinWithStoreRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Quantity,
			&i.StoreID,
			&i.CreatedAt,
			&i.ID_2,
			&i.Name_2,
			&i.Address,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.HashedPassword,
			&i.CreatedAt_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, description, price, quantity, store_id, created_at FROM products
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Quantity,
			&i.StoreID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products SET
name = COALESCE($2, name),
description = COALESCE($3, description),
price = COALESCE($4, price),
quantity = COALESCE($5, quantity)
WHERE id = $1
RETURNING id, name, description, price, quantity, store_id, created_at
`

type UpdateProductParams struct {
	ID          int64          `json:"id"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Price       sql.NullString `json:"price"`
	Quantity    sql.NullInt32  `json:"quantity"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Quantity,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Quantity,
		&i.StoreID,
		&i.CreatedAt,
	)
	return i, err
}
