// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"context"
)

type Querier interface {
	CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error)
	GetStore(ctx context.Context, id int32) (Store, error)
	GetStoreForUpdate(ctx context.Context, id int32) (Store, error)
	ListStores(ctx context.Context, arg ListStoresParams) ([]Store, error)
}

var _ Querier = (*Queries)(nil)
